--KELUARKAN EXCEL HASIL QUERY DI BAWAH
/* RENAME TAB DI EXCEL SESUAI URUTAN
1. PROVISI
2. SUMMARY ALL PK (non imbt)
3. SUMMARY ckpn imbt
*/
----------------------------------------------------------------
--1.     
SELECT *
  FROM AD1SYS.ACCT_PROVISION_RISK_SYAR A
 WHERE A.PERIODE = CASE
         WHEN TRUNC(SYSDATE) = LAST_DAY(TRUNC(SYSDATE)) THEN
          TRUNC(SYSDATE)
         ELSE
          ADD_MONTHS(LAST_DAY(TRUNC(SYSDATE)), -1)
       END;
----------------------------------------------------------------
--2.SUMMARY ALL PK
SELECT A.ACCT_PC_CODE,
       A.ACCT_BR_ID,
       (SELECT T.ACCT_PRODUCT
          FROM AD1SYS.ACCT_PRODUCT_MAPPING_PC_CODE T
         WHERE T.ACCT_PC_CODE = TRIM(A.ACCT_PC_CODE)) PRODUCT_ID,
       A.KEGIATAN_USAHA,
       A.CARA_PEMBIAYAAN,
       A.ACCT_CKPN_PROD_MATRIX,
       A.ACCT_CKPN_PORTFOLIO,
       A.ACCT_CKPN_CHANEL,
       A.ACCT_CKPN_STAGE,
       TRIM(A.ACCT_STATUS_PK) ACCT_STATUS_PK,
       CASE
         WHEN A.ACCT_FIN_TYPE = '1' THEN
          'KONVEN'
         ELSE
          'SYARIAH'
       END FIN_TYPE,
       A.ACCT_COLLECTABILITY_OID,
       AR.ACCT_COLLECTABILITY_OID ACCT_COLLECT_OID_OLD_OJK,
       A.ACCT_SOURCE_AR,
       SUM(A.ACCT_BAL_PRIN) SUM_AR_PRIN,
       SUM(A.ACCT_BAL_INTR) SUM_AR_INTR,
       SUM(A.BOOKING_VALUE) SUM_TAC,
       SUM(A.AP_PRIN) SUM_AP_PRIN,
       SUM(A.AP_INTR) SUM_AP_INTR,
       SUM(A.CKPN_AR_PRIN) SUM_CKPN_AR_PRIN,
       SUM(A.CKPN_AR_INTR) SUM_CKPN_AR_INTR,
       SUM(A.CKPN_TAC) SUM_CKPN_TAC,
       SUM(A.CKPN_AP_PRIN) SUM_CKPN_AP_PRIN,
       SUM(A.CKPN_AP_INTR) SUM_CKPN_AP_INTR,
       SUM(A.CKPN_AR_PRIN_MODEL) SUM_CKPN_AR_PRIN_MODEL,
       SUM(A.CKPN_AR_INTR_MODEL) SUM_CKPN_AR_INTR_MODEL,
       SUM(A.CKPN_AP_PRIN_MODEL) SUM_CKPN_AP_PRIN_MODEL,
       SUM(A.CKPN_AP_INTR_MODEL) SUM_CKPN_AP_INTR_MODEL,
       SUM(NVL(A.DISKON, 0)) DISKON
  FROM AD1SYS.ACCT_CKPN_ALL A, AD1SYS.ACCT_PENCADANGAN_AR AR
 WHERE A.PERIODE = CASE
         WHEN TRUNC(SYSDATE) = LAST_DAY(TRUNC(SYSDATE)) THEN
          TRUNC(SYSDATE)
         ELSE
          ADD_MONTHS(LAST_DAY(TRUNC(SYSDATE)), -1)
       END --tgl Current EOM
   AND AR.ACCT_BR_ID = A.ACCT_BR_ID
   AND AR.ACCT_CONT_NO = A.ACCT_CONT_NO
   AND AR.ACCT_PERIODE = A.PERIODE
   AND NOT EXISTS (SELECT 1
          FROM AD1SYS.ACCT_CKPN_IMBT ACI
         WHERE ACI.ACCT_BR_ID = A.ACCT_BR_ID
           AND ACI.ACCT_CONT_NO = A.ACCT_CONT_NO
           AND ACI.PERIODE = A.PERIODE)
 GROUP BY A.ACCT_PC_CODE,
          A.ACCT_BR_ID,
          A.KEGIATAN_USAHA,
          A.CARA_PEMBIAYAAN,
          A.ACCT_CKPN_STAGE,
          TRIM(A.ACCT_STATUS_PK),
          A.ACCT_CKPN_PROD_MATRIX,
          A.ACCT_CKPN_PORTFOLIO,
          A.ACCT_CKPN_CHANEL,
          A.ACCT_FIN_TYPE,
          A.ACCT_COLLECTABILITY_OID,
          AR.ACCT_COLLECTABILITY_OID,
          A.ACCT_SOURCE_AR;

----------------------------------------------------------------
--3.SUMMARY ckpn PK IMBT
--3.SUMMARY ckpn PK IMBT
SELECT A.ACCT_PC_CODE,
       A.ACCT_BR_ID,
       (SELECT T.ACCT_PRODUCT
          FROM AD1SYS.ACCT_PRODUCT_MAPPING_PC_CODE T
         WHERE T.ACCT_PC_CODE = TRIM(A.ACCT_PC_CODE)) PRODUCT_ID,
       A.KEGIATAN_USAHA,
       A.CARA_PEMBIAYAAN,
       A.ACCT_CKPN_PROD_MATRIX,
       A.ACCT_CKPN_PORTFOLIO,
       A.ACCT_CKPN_CHANEL,
       A.ACCT_CKPN_STAGE,
       TRIM(A.ACCT_STATUS_PK) ACCT_STATUS_PK,
       CASE
         WHEN A.ACCT_FIN_TYPE = '1' THEN
          'KONVEN'
         ELSE
          'SYARIAH'
       END FIN_TYPE,
       A.ACCT_COLLECTABILITY_OID,
       AR.ACCT_COLLECTABILITY_OID ACCT_COLLECT_OID_OLD_OJK,
       A.ACCT_SOURCE_AR,
       SUM(ACI.OS_AR) SUM_OS_AR,
       SUM(ACI.OS_ACCRUED_INTEREST) SUM_OS_ACCRUED_INTEREST,
       SUM(ACI.OS_ASSET) SUM_OS_ASSET,
       SUM(ACI.OS_ADMIN) SUM_OS_ADMIN,
       SUM(ACI.OS_POKOK_IMBT) SUM_OS_POKOK_IMBT,
       SUM(ACI.OS_UJRAH_IMBT) SUM_OS_UJRAH_IMBT,
       SUM(ACI.OS_ACCRUED_POKOK_IMBT) SUM_OS_ACCRUED_POKOK_IMBT,
       SUM(ACI.OS_ACCRUED_UJRAH_IMBT) SUM_OS_ACCRUED_UJRAH_IMBT,
       SUM(ACCT_BDD_IMBT) SUM_ACCT_BDD_IMBT,
       SUM(ACCT_ASSET_KOMISI_IMBT) SUM_ACCT_ASSET_KOMISI_IMBT,
       SUM(ACCT_DISKON_ASR_ASSET_IMBT) SUM_ACCT_DISKON_ASR_ASSET_IMBT,
       SUM(ACCT_BDD_ASR_ASSET) SUM_ACCT_BDD_ASR_ASSET,
       SUM(ACCT_TAC_IMBT) SUM_ACCT_TAC_IMBT,
       SUM(ACI.CKPN_OS_AR) SUM_CKPN_OS_AR,
       SUM(ACI.CKPN_ACCRUED_INTEREST) SUM_CKPN_ACCRUED_INTEREST,
       SUM(ACI.CKPN_AR_ASSET) SUM_CKPN_AR_ASSET,
       SUM(ACI.CKPN_AR_IMBT) SUM_CKPN_AR_IMBT,
       SUM(ACI.CKPN_ADMIN_IMBT) SUM_CKPN_ADMIN_IMBT,
       SUM(ACI.CKPN_AR_ACCRUED_IMBT) SUM_CKPN_AR_ACCRUED_IMBT,
       SUM(ACI.CKPN_UJRAH_IMBT) SUM_CKPN_UJRAH_IMBT,
       SUM(ACI.CKPN_UJRAH_ACRRUED_IMBT) SUM_CKPN_UJRAH_ACRRUED_IMBT,       
       SUM(CKPN_BDD_IMBT) SUM_CKPN_BDD_IMBT, 
       SUM(CKPN_ASSET_KOMISI_IMBT) SUM_CKPN_ASSET_KOMISI_IMBT,
       SUM(CKPN_DISKON_ASR_ASSET_IMBT) SUM_CKPN_DISKON_ASR_ASSET_IMBT,
       SUM(CKPN_BDD_ASR_ASSET) SUM_CKPN_BDD_ASR_ASSET,
       SUM(CKPN_TAC_IMBT) SUM_CKPN_TAC_IMBT
  FROM AD1SYS.ACCT_CKPN_IMBT ACI
  LEFT JOIN AD1SYS.ACCT_PENCADANGAN_AR AR
    ON AR.ACCT_BR_ID = ACI.ACCT_BR_ID
   AND AR.ACCT_CONT_NO = ACI.ACCT_CONT_NO
   AND AR.ACCT_PERIODE = ACI.PERIODE
  LEFT JOIN AD1SYS.ACCT_CKPN_ALL A
    ON ACI.ACCT_BR_ID = A.ACCT_BR_ID
   AND ACI.ACCT_CONT_NO = A.ACCT_CONT_NO
   AND ACI.PERIODE = A.PERIODE
 WHERE ACI.PERIODE = CASE
         WHEN TRUNC(SYSDATE) = LAST_DAY(TRUNC(SYSDATE)) THEN
          TRUNC(SYSDATE)
         ELSE
          ADD_MONTHS(LAST_DAY(TRUNC(SYSDATE)), -1)
       END --tgl Current EOM
 GROUP BY A.ACCT_PC_CODE,
          A.ACCT_BR_ID,
          A.KEGIATAN_USAHA,
          A.CARA_PEMBIAYAAN,
          A.ACCT_CKPN_STAGE,
          TRIM(A.ACCT_STATUS_PK),
          A.ACCT_CKPN_PROD_MATRIX,
          A.ACCT_CKPN_PORTFOLIO,
          A.ACCT_CKPN_CHANEL,
          A.ACCT_FIN_TYPE,
          A.ACCT_COLLECTABILITY_OID,
          AR.ACCT_COLLECTABILITY_OID,
          A.ACCT_SOURCE_AR;
