/*

MOHON UNTUK MENJALANKAN SCRIPT JIKA SUDAH ADA KONFIRMASI DARI PIC (BOWO/YODI/ENO) DI GROUP CLOSING

*/

---------------------------------------------------------------
--STEP 1 (RUN PROSES INSERT PENYAMAAN COLLECT)
---------------------------------------------------------------

-- CEK
SELECT COUNT(1) -- PASTIKAN KE-ISI
  FROM AD1SYS.ACCT_COLLECT_JFBDI A
 WHERE A.PERIODE = TRUNC(SYSDATE) - 1;

SELECT COUNT(1) -- PASTIKAN KOSONG
  FROM AD1SYS.ACCT_FINAL_COLLECT_JF A
 WHERE A.PERIODE = TRUNC(SYSDATE) - 1;

--- MAIN
DECLARE
  DDATE DATE := CASE
                  WHEN TRUNC(SYSDATE) = LAST_DAY(TRUNC(SYSDATE)) THEN
                   TRUNC(SYSDATE)
                  ELSE
                   ADD_MONTHS(LAST_DAY(TRUNC(SYSDATE)), -1)
                END; --tgl Current EOM

BEGIN
  BEGIN
    AD1SYS.PROC_INSERT_COLLECT_BYOID(DDATE); --SESUAIKAN DENGAN EOM CLOSING
  EXCEPTION
    WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR('-20000',
                              'ERROR INSERT PENYAMAAN COLLECT : ' ||
                              SQLERRM);
  END;
END;


--STEP 2 (RUN UPDATE DOMAIN READY FOR HQ & ADD)
UPDATE AD1SYS.PARA_DOMAIN_DTL A
   SET A.HIGH_VALUE = '1'
 --  SELECT * FROM  AD1SYS.PARA_DOMAIN_DTL A
 WHERE A.DOMAIN_ID = 'ECL'
   AND A.DOMAIN_VALUE = 'COLLECT'
   AND A.LOW_VALUE IN ('ADD', 'HQ');



-- CEK
SELECT COUNT(1) -- PASTIKAN KE ISI
  FROM AD1SYS.ACCT_COLLECT_JFBDI A
 WHERE A.PERIODE = TRUNC(SYSDATE) - 1;

SELECT COUNT(1) -- PASTIKAN JUMLAHKAN HAMPIR SAMA DENGAN SCIPT PENGECEKAN ACCT_COLLECT_JFBDI
  FROM AD1SYS.ACCT_FINAL_COLLECT_JF A
 WHERE A.PERIODE = TRUNC(SYSDATE) - 1;
