--STEP 1 INSERT DATA
--CEK
-- PASTIKAN SOURCE( OBLIGOR ) DATANYA KOSONG
SELECT SUM(NVL(R.ACCT_ACCRUED_TOTAL, 0)), 'PENCADANGAN AR' SOURCE
  FROM AD1SYS.ACCT_PENCADANGAN_AR R
 WHERE R.ACCT_PERIODE = CASE
         WHEN TRUNC(SYSDATE) = LAST_DAY(TRUNC(SYSDATE)) THEN
          TRUNC(SYSDATE)
         ELSE
          ADD_MONTHS(LAST_DAY(TRUNC(SYSDATE)), -1)
       END
   AND R.ACCT_COLLECTABILITY_OID_BI <= 2
   AND NVL(R.ACCT_ACCRUED_TOTAL, 0) <> 0
   AND R.ACCT_ACCRUED_STATUS = 1
   AND R.STATUS = 'AKTIF'
   AND NOT EXISTS (SELECT 1
          FROM AD1SYS.ACCT_FINAL_COLLECT_JF B
         WHERE B.CONTRACT_NUMBER = R.ACCT_CONT_NO
           AND B.BRANCH = R.ACCT_BR_ID
           AND B.PERIODE = R.ACCT_PERIODE
           AND B.COLLECTABILITY > 2)
UNION ALL
SELECT SUM(A.ACCT_OVRD_ACCRUED + A.ACCT_CURR_ACCRUED), 'OBLIGOR' SOURCE
  FROM AD1SYS.ACCT_AREC_ACCRUED_OBLIGOR A
 WHERE A.ACCT_ACCR_PERIOD = CASE
         WHEN TRUNC(SYSDATE) = LAST_DAY(TRUNC(SYSDATE)) THEN
          TRUNC(SYSDATE)
         ELSE
          ADD_MONTHS(LAST_DAY(TRUNC(SYSDATE)), -1)
       END;
